
task 2.4: Boolean functions and the Boolean Fourier transform
------------

Import all necessary library

In [53]:
import numpy as np
import numpy.linalg as la
import numpy.random as rnd
import matplotlib.pyplot as plt
import itertools as iter

We initialise the traning samples

In [54]:
def data_matrix():
    # create design n X m input matrix (design matrix)
    # where n is the number of data avalible, m is the number of feature +1
    X = np.matrix([[1.0,  1.0,  1.0,  1.0],
                   [1.0,  1.0,  1.0, -1.0],
                   [1.0,  1.0, -1.0,  1.0],
                   [1.0,  1.0, -1.0, -1.0],
                   [1.0, -1.0,  1.0,  1.0],
                   [1.0, -1.0,  1.0, -1.0],
                   [1.0, -1.0, -1.0,  1.0],
                   [1.0, -1.0, -1.0, -1.0]]) 
    
    #create different output to the input matrix based on rules 110 and 126
    y110 = np.matrix([[-1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0, -1.0]]).T
    y126 = np.matrix([[-1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0]]).T

    return X, y110, y126

To find the parameter $\omega$ which minimise the square error

$$E(\omega)=||X\omega - y||^2$$


We can use least squares solution as follows:
$$\omega=(X^{T}-X)X^{T}y.$$


Reference: Bauckhage, Christian. "NumPy/SciPy Recipes for Data Science: Ordinary Least Squares Optimization." researchgate. net, Mar (2015).

In [55]:
def lsq_solution(X, y):
    w = np.dot(np.dot(la.inv(np.dot(X.T, X)), X.T), y)
    return w

Calculate the predicated output $\hat{y}$ given the input data $X$ and the weight vector $\omega$

In [56]:
def prediction(X,w):
    print '\n***** predicted Y *****'
    return w.T*X.T

Get the Input vector $X$ and the output for rule 110 and 126

In [57]:
X,y110,y126= data_matrix()

Estimate the weights for rule 110

In [58]:
w110= lsq_solution(X, y110)
print w110

[[ 0.25]
 [ 0.25]
 [-0.25]
 [-0.25]]


Predicate rule 110 using the estimated weight vector w110

In [59]:
print prediction(X, w110)


***** predicted Y *****
[[ 0.   0.5  0.5  1.  -0.5  0.   0.   0.5]]


============

Similarly for rule 126

In [60]:
w126= lsq_solution(X, y126)
print w126

[[ 0.5]
 [ 0. ]
 [ 0. ]
 [ 0. ]]


In [61]:
print prediction(X, w126)


***** predicted Y *****
[[ 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5]]


A polynomial solution
------------
We replacing the design matrix $X$ with a feature matrix matrix $\Phi$

Create xor to calculate the parity functions

In [62]:
def xor(list):
    
    xor=int(list[0]) ^ int(list[1])
    i=1
    while i<len(list)-1:
        xor=xor^int(list[i+1])
        i+=1
    return xor  

Get power set from a list of elements

In [63]:
def get_power_set(element_list):
    
    set=[]
    for i in range(1,len(element_list)+1):
        set+= list( iter.combinations(element_list, i) )
        
    return set   

Create the parity function from the powerset

In [64]:
def basis_parity_func(power_set):
    
    parity_output=[1]
    for element in power_set:
        E=[(e+1)/2 for e in element] 
        
        if len(E)>1:
            parity=xor(E)
        else:
            parity=int(E[0])
        
        
        parity_output.append(parity)

    return parity_output

Get the feature matrix $\Phi$ from the design matrix $X$

In [65]:
def get_feature_matrix(X):
    
    X=np.delete(X,0,axis=1)
    
    n_row=X.shape[0]
    
    feature_materix=[]
    for r in range(n_row):
        X_row=X[r,].tolist()[0]
        power_set = get_power_set(X_row)
        parity_output= basis_parity_func(power_set)
        feature_materix.append(parity_output)
        
    feature_materix = np.array(feature_materix)
    
    return feature_materix

Get the feature matrix

In [68]:
feature_matrix= get_feature_matrix(X)
print feature_matrix

[[1 1 1 1 0 0 0 1]
 [1 1 1 0 0 1 1 0]
 [1 1 0 1 1 0 1 0]
 [1 1 0 0 1 1 0 1]
 [1 0 1 1 1 1 0 0]
 [1 0 1 0 1 0 1 1]
 [1 0 0 1 0 1 1 1]
 [1 0 0 0 0 0 0 0]]


Estimate the weights for rule 110 from the feature matrix $\Phi$

In [74]:
w110= lsq_solution(feature_matrix, y110)
print w110

[[-1. ]
 [ 0.5]
 [-0.5]
 [-0.5]
 [ 0.5]
 [ 0.5]
 [ 1.5]
 [ 0.5]]


Predicate rule 110 using the estimated weight vector w110

In [75]:
print prediction(feature_matrix, w110)


***** predicted Y *****
[[-1.  1.  1.  1. -1.  1.  1. -1.]]


============

Similarly for rule 126}


In [78]:
w126= lsq_solution(feature_matrix, y126)
print w126

[[-1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]]


In [79]:
print prediction(feature_matrix, w126)


***** predicted Y *****
[[-1.  1.  1.  1.  1.  1.  1. -1.]]
